### ISSUE TITLE
Modify schedule switch to On/Off/Auto

### ISSUE THREAD

**Issue by AndyKirby** [nielsfaber/scheduler-component#329] opened 2024-02-02 11:49 UTC
### Checklist
- [x ] I checked for similar existing requests (both open and closed) before posting.
- [x ] My request is generic, other users may benefit from it too.

### Proposal
The current switch item on the schedule card enables/disables the schedule and this can fight with other manual control of the scheduled entities. Notably when controlling lights or security lights making the user experience either sub optimal or clunky.

The proposal is to modify the switch from a bi positional switch to a tri positional switch featuring On/Off/Auto positions. Instead of the current enable/disable schedule.

Where the 3 positions can be one of the two following (Selected in the options for the schedule)

Option 1 Manual/Auto:-
On, Scheduled entities switched on and the schedule ignored.
Off, Scheduled entities switched off and the schedule ignored.
Auto, entities switched as per schedule.

Option 2 Advance/Auto:-
On, Scheduled entities switched on until next scheduled off and then switch returns to auto.
Off, Scheduled entities switched off until next scheduled on and then switch returns to auto.
Auto, entities switched as per schedule.

I guess it might be useful to expose the switch in some way as an entity for automation purposes too.

It will also have the side effect of making the UI less cluttered removing the need for both separate schedule and manual controls by rolling the function into one easier to use item.

**Comment by AndyKirby** [comment] 2024-02-02 12:01
Just thought an alternative might be to have Option 1 and a button for Advance on the ui giving both options without needing to set options.

Apols for the late breaking suggestion. It only came to me after submitting the above.

**Comment by AndyKirby** [comment] 2024-02-02 16:43
I am not sure how much of the proposals solution would be the card component or the scheduler component so have posted this request to both as i suspect there might be an element of both needed to do this. Apols if one is unnecessary.

**Comment by nielsfaber** [comment] 2024-02-22 05:31
Duplicate of https://github.com/nielsfaber/scheduler-card/issues/795

**Closed by nielsfaber** 2024-02-22 05:31 UTC
