### ISSUE TITLE
Ability to schedule group of entites

### ISSUE THREAD

**Issue by goull** [nielsfaber/scheduler-component#51] opened 2020-11-11 11:55 UTC
Request: check multiple entities add same schedule
Example: set TV, BluRay, Ps4 on at same time
![Senza titolo-2](https://user-images.githubusercontent.com/11614967/98808861-1a5ebd00-241d-11eb-8b75-0edaa425a06b.png)

**Comment by nielsfaber** [comment] 2020-11-11 15:08
I am planning to add this function (soon).
Give it a couple of weeks... Hopefully by end of the month.
For now, consider to make a HA group entity for it.

Duplicate of: https://github.com/nielsfaber/scheduler-card/issues/73 
Therefore -> closing

**Closed by nielsfaber** 2020-11-11 15:08 UTC
Labels: enhancement
