### ISSUE TITLE
Feature Request: Random Time Offset

### ISSUE THREAD

**Issue by sstefanowski** [nielsfaber/scheduler-component#25] opened 2020-09-23 11:18 UTC
Hi Neil,
I must admit your solution is perfect in simplicity. Congratulations on the concept!

I was wondering if you could consider as useful implementing "random time offset" for the trigger of the action. It could work in a way that something is triggered "around planned time" - with a random offset of e.g. +-2h. Such a feature could be useful as "security feature" - for turning on and off the lights simulating a presence in home/apartment, as randomness would prevent realizing that lights are turned on and off by scheduled automation.
What do you think?

Thank you again for this awesome component.

**Comment by nielsfaber** [comment] 2020-09-23 12:09
Please check https://github.com/nielsfaber/scheduler-card/issues/26
Someone else asked for the same thing.
I think it is quite doable. Just need to find a good way to make it configurable in the card.
Currently this is not a priority, so it will take some patience.

**Comment by KTibow** [comment] 2020-09-23 13:36
Duplicate of #26, consider closing, commenting there, and leaving a 👍

**Comment by sstefanowski** [comment] 2020-09-23 15:17
Hi Guys,

So, it's more like card-related-feature? Really?

I thought such a feature must be just implemented in scheduler-component first. I imagined scheduler-card is just displaying scheduler config but takes no part during scheduled execution. I thought randomness of consecutive calls must be calculated by scheduler during the "waiting" phase?

But if you confirm it's better to leave the feature on scheduler-card feature list I'll close this thread...

**Comment by nielsfaber** [comment] 2020-09-23 15:28
You're 100% correct. 
The scheduler card is just a GUI that calls services to make changes to the scheduler-component, which does all the time-keeping magic.
The main challenge here will be to make them work together, so adding a property to schedule entities, defining the amount of randomness to add to the times. And then making it read/writable for the card.
I don't mind if you keep it open, but it **_is_** a duplicate feature request.

**Comment by dio45rus** [comment] 2020-10-21 04:47
Hello! A card works fine, but ten minutes when setting the event time is too much, How I can a change to 5 or 1 minutes interval?

**Comment by dio45rus** [comment] 2020-10-21 15:09
> @dio45rus wrong place, make a new issue or post in the forum. Anyway read the docs, or use the UI editor:
> ![image](https://user-images.githubusercontent.com/10727862/96730761-644b0a80-136b-11eb-9dc2-ddf3a1ba394b.png)

Read the docs? Are you seriously??? Nobody read a docs. Thanx anyway.

**Comment by nielsfaber** [comment] 2020-10-21 15:15
> Read the docs? Are you seriously??? Nobody read a docs. Thanx anyway.

Watch your tone please.
I agree with @KTibow 

It seems like you haven't taken the effort to look for an answer to your question.
Github is only intended for reporting bugs/issues or feature requests, not for personal assistance.
Your question is completely off-topic in this discussion anyway..

**Comment by nielsfaber** [comment] 2020-11-03 07:02
Time to clean up old issues.. Please re-open if the issue is not resolved.

The original request is kept open.

**Closed by nielsfaber** 2020-11-03 07:02 UTC
Labels: duplicate
