### ISSUE TITLE
Warning from Home Assistant, Home Assistant deaktiviert die Funktion bei Version 2024.9

### ISSUE THREAD

**Issue by Johnyboy1984** [nielsfaber/scheduler-component#338] opened 2024-03-12 21:31 UTC
Ok

### Checklist
- [yes ] I checked for similar existing issues (both open and closed) before posting.
- [yes ] I am running the latest version.

### Expected behavior
[What you expected to happen]

### Actual behavior
[What actually happened]

Logger: homeassistant.helpers.frame
Quelle: helpers/frame.py:156
Erstmals aufgetreten: 22:17:23 (2 Vorkommnisse)
Zuletzt protokolliert: 22:17:27

Detected that custom integration 'scheduler' accesses hass.components.websocket_api. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from websocket_api directly at custom_components/scheduler/websockets.py, line 235: hass.components.websocket_api.async_register_command(, please create a bug report at https://github.com/nielsfaber/scheduler-component/issues
Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
### Steps to Reproduce
Logger: homeassistant.helpers.frame
Quelle: helpers/frame.py:156
Erstmals aufgetreten: 22:17:23 (2 Vorkommnisse)
Zuletzt protokolliert: 22:17:27

Detected that custom integration 'scheduler' accesses hass.components.websocket_api. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from websocket_api directly at custom_components/scheduler/websockets.py, line 235: hass.components.websocket_api.async_register_command(, please create a bug report at https://github.com/nielsfaber/scheduler-component/issues
Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues

**Comment by nielsfaber** [comment] 2024-03-13 13:47
Duplicate of #336.

**Closed by nielsfaber** 2024-03-13 13:47 UTC
Labels: bug
