### ISSUE TITLE
Error doing job: Task exception was never retrieved - Scheduler never perform the action

### ISSUE THREAD

**Issue by dj4ngo** [nielsfaber/scheduler-component#53] opened 2020-11-13 17:05 UTC
I am using HASS v0.117.6
I just performed a fresh install, to reproduce in a minimal environment, then installed latest HACS (v1.6.2) and installed both scheduler integration and card.

I want to control some input_select only.

When the timer is performing the action (changing the input_select), it faced this issue.
I tried it with a schema and an option and faced the same issue. The input_select is never updated due to this issue.

-------------------
Issue :
```
2020-11-13 17:57:00 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/scheduler/switch.py", line 279, in async_timer_finished
    # execute the action
  File "/config/custom_components/scheduler/switch.py", line 318, in async_execute_command
  File "/config/custom_components/scheduler/switch.py", line 361, in async_queue_action
    if res:
  File "/config/custom_components/scheduler/switch.py", line 401, in async_execute_action
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 91, in async_call_from_config
    await hass.services.async_call(*parms, blocking, context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1402, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 340, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 336, in _exec
    v = func(v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['mode']

```

**Comment by nielsfaber** [comment] 2020-11-13 17:07
Duplicate of your other issue report?

**Comment by dj4ngo** [comment] 2020-11-13 17:14
No, this is a different one. 

The other was relative to an issue when editing the schedule through the card. 

This one is relative to a non-execution of the action when the schedule reach the timer. 
It is supposed to change my input_select to a new value, but does apparently nothing (no error pop-up). 

When I had a look on the logs I saw that this was this  error this time : Error doing job: Task exception was never retrieved

**Comment by nielsfaber** [comment] 2020-11-13 17:16
The real error is: 
```voluptuous.error.MultipleInvalid: extra keys not allowed @ data['mode']```
Which is the same as in your other issue.

Should be taken care of with the change I just made.

**Comment by KTibow** [comment] 2020-11-13 17:17
Why would an error pop up? Where would it pop up?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dj4ngo** [comment] 2020-11-13 17:20
Ok, my bad, same root cause so. 

@KTibow: I am talking about a pop on the bottom left corner which appears sometimes. 
I didn't had a look closer on how hass is working internally, but this is a notification manages by homeassistant itself and not relative to the scheduler.

**Comment by dj4ngo** [comment] 2020-11-13 17:40
duplicate of #52

**Closed** 2020-11-13 17:40 UTC
