### ISSUE TITLE
TRV TS0601 absent mode cannot be used anymore 

### ISSUE THREAD

**Issue by pbranly** [nielsfaber/scheduler-component#221] opened 2022-11-12 17:35 UTC
Hi
I have a thermostat type TS601 that supports away mode.
I can use it with the sensors that are available in HA via mqtt.
The scheduler is programmed to use the away mode at a given time and was working.

i noticed today that the TRV did not switched in away mode while it was working before .
I join a screen copy that shows that this mode was present when I programmed it along time ago 
I join as well a screen copy of the tentative to create a new schedule. The mode await is not present anymore in the possibilities 

I can supply any other details for help.

phil

![9F13AA37-1D00-42C3-BCAF-DF64C3D897FD](https://user-images.githubusercontent.com/22018509/201487145-bc58f55f-73fa-4aaa-8955-0623b3c46fc0.jpeg)
![D15A2003-08D9-44A1-95C9-A0246CBEB887](https://user-images.githubusercontent.com/22018509/201487148-92c4b344-e35a-41c8-94ed-e368db0c488e.jpeg)

**Comment by nielsfaber** [comment] 2022-11-13 05:57
> I join as well a screen copy of the tentative to create a new schedule. The mode await is not present anymore in the possibilities

Please go to developer tools -> States and find the climate entity. Can you provide a screenshot of all the properties of this device?
There should be a property `preset_modes` which should include the `away` preset if it is supported. 

> i noticed today that the TRV did not switched in away mode while it was working before .

This could be caused by either the device or by scheduler.
You could check the logbook entry of your climate entity to see what happened at the programmed time.
You can check what is sent by scheduler by enabling debug logging.
You can do this by adding this to the configuration.yaml (requires restarting HA):
```yaml
logger:
  default: warning
  logs:
    custom_components.scheduler: debug
```
The HA log should show a lot of info regarding what scheduler does at the programmed times.
Please post the results.

**Comment by pbranly** [comment] 2022-11-13 06:23
Hi thank you for the answer:
Log gives:

2022-11-13 07:15:00.041 WARNING (MainThread) [homeassistant.components.mqtt.climate] 'away' is not a valid preset mode

And supported modes are:
![705BD4D2-01F1-47FE-9FD8-66C8DFD72537](https://user-images.githubusercontent.com/22018509/201508796-0b7221c9-326c-475f-905b-5b571ae08533.png)
![EC9A2415-F737-41E6-BF8B-73C9C4709F32](https://user-images.githubusercontent.com/22018509/201508798-5886c5b6-dc9d-43f7-8ac6-24ce2dbafc6a.png)

regards
Phil

**Comment by pbranly** [comment] 2022-11-13 06:37
I think I have fixed the issue . I use now a switch to control that feature and it works. I suspect that away mode was removed from the presets between last winter ad now.
I did not noticed that because all my TRV were deactivated 
Phil

**Comment by nielsfaber** [comment] 2022-11-13 11:10
It indeed looks like your device does not support the away preset (anymore).
The issue is not caused by scheduler.
I will close this item.

**Closed by nielsfaber** 2022-11-13 11:10 UTC
Labels: bug
