### ISSUE TITLE
Schedule is triggered, but only with comfort settings

### ISSUE THREAD

**Issue by Micha-Btz** [nielsfaber/scheduler-component#157] opened 2021-12-11 11:07 UTC
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
I have created a heating schedule which should start at 6 am at 28°C and switching at 9am to 21°C the comfort temperature.

### Actual behavior
the schedule is triggered at 6 am as designed, but only on 21°C degrees comfort temp.
I'm not sure if it is a bug or a limitation on the thermostats. 
thermostats can be switched by hand to 28°C degrees.
![Bildschirmfoto_2021-12-11_11-50-26](https://user-images.githubusercontent.com/4420944/145674268-ea4913e5-e8ed-4343-b4dc-16d9e0082a34.png)

Please tell me if you need some more infos.

Micha

**Comment by nielsfaber** [comment] 2021-12-11 11:59
I don't quite follow your problem report.
> the schedule is triggered at 6 am as designed, but only on 21°C degrees comfort temp.

From your screenshot I don't see any action planned at 06:00.
I see comfort temp starting at 09:00, heating to 28C planned at around 06:30.
Which one is the one giving problems?

To check what is actually sent by Scheduler, you can enable debug logging, it is described here: https://github.com/nielsfaber/scheduler-component/issues/136#issuecomment-979792265

You can also check the history and logbook to see how the thermostat responds. This is described here: https://github.com/nielsfaber/scheduler-component/issues/136#issuecomment-950058203

If the thermostat does not repond correctly to the command for heating to 28C fails, please follow the procedure here to reproduce and tune the behaviour: https://github.com/nielsfaber/scheduler-component/issues/136#issuecomment-990192101

Please share your findings.

**Comment by Micha-Btz** [comment] 2021-12-12 09:52
![Bildschirmfoto_2021-12-12_10-41-22](https://user-images.githubusercontent.com/4420944/145707608-7e5441f4-ac9e-4089-81a7-61e6bebe6f55.png)
```

2021-12-12 06:00:00 DEBUG (MainThread) [custom_components.scheduler.timer] Timer 7d59ae has reached slot 1
2021-12-12 06:00:00 DEBUG (MainThread) [custom_components.scheduler.switch] Schedule 7d59ae is triggered, proceed with actions
2021-12-12 06:00:00 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_temperature on entity climate.wohnzimmer_li
2021-12-12 06:00:00 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Postponing next action for 5 seconds
2021-12-12 06:00:00 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_temperature on entity climate.wohnzimmer_re
2021-12-12 06:00:00 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Postponing next action for 5 seconds
2021-12-12 06:00:05 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_hvac_mode on entity climate.wohnzimmer_li
2021-12-12 06:00:05 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_hvac_mode on entity climate.wohnzimmer_re
2021-12-12 06:00:05 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: finished execution of actions
2021-12-12 06:01:00 DEBUG (MainThread) [custom_components.scheduler.timer] Timer of 7d59ae set for 2021-12-12 10:20:00+01:00
2021-12-12 09:28:56 DEBUG (MainThread) [custom_components.scheduler.timer] Timer of 7d59ae set for 2021-12-12 10:20:00+01:00
2021-12-12 09:28:56 DEBUG (MainThread) [custom_components.scheduler.switch] Schedule 7d59ae is starting in a timeslot, proceed with actions
2021-12-12 09:28:56 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_temperature on entity climate.wohnzimmer_li
2021-12-12 09:28:56 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Postponing next action for 5 seconds
2021-12-12 09:28:56 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_temperature on entity climate.wohnzimmer_re
2021-12-12 09:28:56 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Postponing next action for 5 seconds
2021-12-12 09:29:01 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_hvac_mode on entity climate.wohnzimmer_li
2021-12-12 09:29:01 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_hvac_mode on entity climate.wohnzimmer_re
2021-12-12 09:29:01 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: finished execution of actions

2021-12-12 09:31:56 DEBUG (MainThread) [custom_components.scheduler.timer] Timer of 2056be set for 2021-12-13 00:00:00+01:00
2021-12-12 09:31:56 DEBUG (MainThread) [custom_components.scheduler.timer] Timer of 7d59ae set for 2021-12-12 10:20:00+01:00
2021-12-12 09:31:56 DEBUG (MainThread) [custom_components.scheduler.switch] Schedule 7d59ae is starting in a timeslot, proceed with actions
2021-12-12 09:31:56 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: service climate.set_temperature is unavailable, action is postponed
2021-12-12 09:31:56 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: service climate.set_temperature is unavailable, action is postponed
2021-12-12 09:34:19 DEBUG (MainThread) [custom_components.scheduler.timer] Timer of 7d59ae set for 2021-12-12 10:00:00+01:00
2021-12-12 09:34:19 DEBUG (MainThread) [custom_components.scheduler.switch] Schedule 7d59ae is starting in a timeslot, proceed with actions
2021-12-12 09:34:19 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_temperature on entity climate.wohnzimmer_li
2021-12-12 09:34:19 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Postponing next action for 15 seconds
2021-12-12 09:34:19 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_temperature on entity climate.wohnzimmer_re
2021-12-12 09:34:19 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Postponing next action for 15 seconds
2021-12-12 09:34:34 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_hvac_mode on entity climate.wohnzimmer_li
2021-12-12 09:34:34 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_hvac_mode on entity climate.wohnzimmer_re
2021-12-12 09:34:34 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: finished execution of actions
2021-12-12 10:00:00 DEBUG (MainThread) [custom_components.scheduler.timer] Timer 7d59ae has reached slot 2
2021-12-12 10:00:00 DEBUG (MainThread) [custom_components.scheduler.switch] Schedule 7d59ae is triggered, proceed with actions
2021-12-12 10:00:00 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_temperature on entity climate.wohnzimmer_li
2021-12-12 10:00:00 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Postponing next action for 15 seconds
2021-12-12 10:00:00 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_temperature on entity climate.wohnzimmer_re
2021-12-12 10:00:00 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Postponing next action for 15 seconds
2021-12-12 10:00:15 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_hvac_mode on entity climate.wohnzimmer_li
2021-12-12 10:00:15 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_hvac_mode on entity climate.wohnzimmer_re
2021-12-12 10:00:15 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: finished execution of actions
2021-12-12 10:01:00 DEBUG (MainThread) [custom_components.scheduler.timer] Timer of 7d59ae set for 2021-12-12 12:30:00+01:00
```
there are no logbook entry for climate.wohnzimmer_re / climate.wohnzimmer_li only for the switch.
For test I have the first started at 6 am until 10 am at 28°C , form 10 am until 12:30 at 25°C and from12:30 till 10pm at the comfort temperature.
What actually happens is, that the temp from 6 am till 12:30 am is set to comfort too. I have set the CONF_SERVICE_DATA to 15. Seems to make no difference.

**Comment by Micha-Btz** [comment] 2021-12-12 09:57
![Bildschirmfoto_2021-12-12_10-55-45](https://user-images.githubusercontent.com/4420944/145707957-95096d44-0582-4f97-ac23-8eba4e7e5b15.png)

Maybe the thermostats are the problem, it can take up to 10min to reconnect via dect.

**Comment by nielsfaber** [comment] 2021-12-12 10:05
For FritzDect thermostat there is a known issue which is discussed here: https://github.com/home-assistant/core/issues/60823
It seems that the thermostat automatically switches to the comfort temperature when setting the operation mode to `heat`, and it ignores the temperature setting which is sent.

You will probably see the same behaviour with the standard [thermostat card](https://www.home-assistant.io/lovelace/thermostat/), when choosing a temperature (via the circle) first, then clicking on the flame icon, which shows it is an internal problem.

Therefor I don't think there is much I can do about it in scheduler.

**Comment by Micha-Btz** [comment] 2021-12-12 10:13
In the thermostat card I can choosing a temperature and this will be transported right to the thermostats. So in general it works.
I will take a look on the issue in the core, maybe there will be a solution. 
Thanks for pointing me in the right direction.

**Comment by pachi81** [comment] 2021-12-12 10:47
I have the same problem with my fritz thermostat.
Is it possible to execute the set hvac command before setting the temperature?
Or do not execute the heat command if it is already in state heat?

**Comment by Micha-Btz** [comment] 2021-12-13 13:03
Maybe set up all temperatures to absolute values work, when the pre defined modes are not used.

**Comment by pachi81** [comment] 2021-12-13 13:20
I implemented a workaround for this using the customize part of the scheduler card

```
customize:
  climate.arbeitszimmer_hkr:
    actions:
      - service: climate.set_temperature
        name: Temperatur setzen
        variables:
          temperature:
            name: Temperatur
            min: 10
            max: 28
            step: 0.5
            unit: °C
        icon: mdi:thermometer
```

Is there a wildcard support for customize (like customize_glob or customize_domain)? Otherwise I have to do this for each entity.
Is it possible to add the "climate.set_temperature" as default action? I only have as default: switch off, set heat and set preset.

Thank you!

Regards, Michael

**Comment by mithomas** [comment] 2021-12-13 14:36
@nielsfaber:

As mentioned in (admittedly long-closed) issue #188 one way of allowing the scheduler card to work work the AVM thermostats would be to always also allow _set temperature_ instead of _heat_ even if the climate entity does support the latter.

This would get rid of the problematic `hvac_mode=heat` for the price of a more complicated UI - for a naive user the difference between the two would most certainly be unclear.

Currently work around this with an overridden _fritzbox_ component where the `async_set_hvac_mode` call is omitted. 

Long-term, I'll move the all schedules back into the FRITZ!Box itself and only trigger respective templates from HA (first step towards this is to integrate template support on the library side in hthiery/python-fritzhome#52, from there it is either a respective service in _fritzbox_ or in an own custom-component). This would also have the advantage of the schedule being visible and available offline directly on the thermostats.

**Comment by pachi81** [comment] 2021-12-13 21:21
@nielsfaber Yes, you are right, for the few people with the fritz!dect devices, the workaround is working well. 
And with your change, this workaround will not be needed. Great work!
Thank you!

**Comment by Micha-Btz** [comment] 2021-12-16 06:25
@pachi81 
where and how do you add your workaround?

**Comment by pachi81** [comment] 2021-12-16 07:52
> @pachi81 where and how do you add your workaround?

The customize has nothing to do with the HA customize settings (I did it wrong the first time...). You have to set the customize part as part of the scheduler-card using the yaml code editor for this card.

**Comment by HelmutEsterer** [comment] 2021-12-16 18:17
Hello,

many, many thanks to pachi81 and niels!

I searched and searched and searched for the file to customize.... ;-(((
**- You give the the essential hint for me to add the customization text to the scheduler-card!**
(I didn't see it before.)

IMHO is this in generally the solution for the problems with AVM (Fritz) thermostate.

@nielsfaber 

Again IMHO, there is no need for changing the code, only a big hint in the documentation i sufficient.
(This is the solution for the issue I reported last year in december with HVAC-Mode on AVM-Thermostate.)

With best regards

Helmut Esterer

**Comment by marcis92** [comment] 2021-12-16 21:50
Hi all,

i'm facing the same issues after updating to latest version 3.2.4 with my Fritz thermostats.
With version 3.2.2 and older everything worked well for like weeks/months.

After a downgrade back to to 3.2.2 its working again like a charm for me without the customization.
I thought it would be maybe worth mentioning for searching for the issue.

If you need anything from me, just let me know.

**Comment by nielsfaber** [comment] 2021-12-17 10:35
I released a new version 3.2.5 of the scheduler-component. This version should set temperature **after** the mode to improve the compatibility with the Fritzbox component.
The workaround described in https://github.com/nielsfaber/scheduler-component/issues/157#issuecomment-992470573 should not be needed anymore.
@Micha-Btz Could you please test this and let me know if it works OK now?

**Comment by pachi81** [comment] 2021-12-17 18:55
@nielsfaber I have installed the new version and reboot my HA.
Then I have tested it, but it does not seems to work!
I have no log messages, only the trigger in the logbook. I also tested it using a script:
1. Set temp
2. Set hvac to heat
3. Set same temp again
This is working like expected, even without step 1.
@Micha-Btz can you also check it?

**Comment by Micha-Btz** [comment] 2021-12-18 07:52
I have updated to the latest release, but it has the same behaviour like before. the comfort setting is used and a directly configured temperature is ignored.

```
2021-12-18 00:00:00 DEBUG (MainThread) [custom_components.scheduler.timer] Timer 7d59ae has reached slot 0
2021-12-18 00:00:00 DEBUG (MainThread) [custom_components.scheduler.switch] Schedule 7d59ae is triggered, proceed with actions
2021-12-18 00:00:00 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_preset_mode on entity climate.wohnzimmer_li
2021-12-18 00:00:00 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_preset_mode on entity climate.wohnzimmer_re
2021-12-18 00:00:00 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Finished execution of actions
2021-12-18 00:01:00 DEBUG (MainThread) [custom_components.scheduler.timer] Timer of 7d59ae set for 2021-12-18 06:00:00+01:00
2021-12-18 06:00:00 DEBUG (MainThread) [custom_components.scheduler.timer] Timer 7d59ae has reached slot 1
2021-12-18 06:00:00 DEBUG (MainThread) [custom_components.scheduler.switch] Schedule 7d59ae is triggered, proceed with actions
2021-12-18 06:00:00 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_temperature on entity climate.wohnzimmer_li
2021-12-18 06:00:00 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Postponing next action for 5 seconds
2021-12-18 06:00:00 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_temperature on entity climate.wohnzimmer_re
2021-12-18 06:00:00 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Postponing next action for 5 seconds
2021-12-18 06:00:05 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_hvac_mode on entity climate.wohnzimmer_li
2021-12-18 06:00:05 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Action has no effect, skipping
2021-12-18 06:00:05 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_temperature on entity climate.wohnzimmer_li
2021-12-18 06:00:05 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_hvac_mode on entity climate.wohnzimmer_re
2021-12-18 06:00:05 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Action has no effect, skipping
2021-12-18 06:00:05 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_temperature on entity climate.wohnzimmer_re
2021-12-18 06:00:05 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Finished execution of actions
2021-12-18 06:01:00 DEBUG (MainThread) [custom_components.scheduler.timer] Timer of 7d59ae set for 2021-12-18 09:00:00+01:00
```

**Comment by nielsfaber** [comment] 2021-12-18 08:21
Thanks for testing, too bad it doesn't work as I intended.
Let's break it down to the actions scheduler performs on one entity.

Step 1:  climate is set to the desired setpoint together with HVAC mode=heat -> OK
```
Executing service climate.set_temperature on entity climate.wohnzimmer_re
Postponing next action for 5 seconds
```

Step 2: climate is set (again) to hvac_mode=heat (only useful for devices which don't support setting hvac_mode together with setpoint). Scheduler saw the device is already in hvac_mode=heat, so skipped
```
Executing service climate.set_hvac_mode on entity climate.wohnzimmer_re
Action has no effect, skipping
```

Step 3: step 1 is repeated again. Apparently the scheduler detected that the setpoint set in step 1 has not been applied (fritzbox sets it back to comfort mode), so scheduler retries.
```
Executing service climate.set_temperature on entity climate.wohnzimmer_re
Finished execution of actions
```

The only thing I can think of as cause for the problem, is that step 3 is identical to step 1.
It means that the set_temperature service is called, together with hvac_mode=heat as parameter (as defined in the [HA docs](https://www.home-assistant.io/integrations/climate/#service-climateset_temperature)).
If fritzbox has no internal logic to compare current hvac_mode with the requested hvac_mode, it could simply execute the whole routine and also end up in the comfort temperature.

To check if this is the case, we could change this line:
https://github.com/nielsfaber/scheduler-component/blob/89efd47254306d4eba4e6f58a62978906c2c19b6/custom_components/scheduler/actions.py#L94

To filter out the hvac_mode and only set the temperature, like so:
```python
                CONF_SERVICE_DATA: {
                    x: service_call[CONF_SERVICE_DATA][x]
                    for x in service_call[CONF_SERVICE_DATA]
                    if x != ATTR_HVAC_MODE
                }
```

I do think that fritzbox is the real troublemaker here, just want to help to improve compatibility from scheduler.
If anyone here is willing to test my proposed change, please let me know the results.

**Comment by Micha-Btz** [comment] 2021-12-18 10:31
After I have checked that I need two curly bracket at the end, it works. :-)

For information I don't set anything beside the comfort and spare temp in fritzbox.

```
2021-12-18 11:16:51 DEBUG (MainThread) [custom_components.scheduler.timer] Timer of 7d59ae set for 2021-12-18 11:30:00+01:00
2021-12-18 11:16:51 DEBUG (MainThread) [custom_components.scheduler.switch] Schedule 7d59ae is starting in a timeslot, proceed with actions
2021-12-18 11:16:51 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_temperature on entity climate.wohnzimmer_li
2021-12-18 11:16:51 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Postponing next action for 5 seconds
2021-12-18 11:16:51 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_temperature on entity climate.wohnzimmer_re
2021-12-18 11:16:51 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Postponing next action for 5 seconds
2021-12-18 11:16:56 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_hvac_mode on entity climate.wohnzimmer_li
2021-12-18 11:16:56 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Action has no effect, skipping
2021-12-18 11:16:56 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_temperature on entity climate.wohnzimmer_li
2021-12-18 11:16:56 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_hvac_mode on entity climate.wohnzimmer_re
2021-12-18 11:16:56 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Action has no effect, skipping
2021-12-18 11:16:56 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Executing service climate.set_temperature on entity climate.wohnzimmer_re
2021-12-18 11:16:56 DEBUG (MainThread) [custom_components.scheduler.actions] [7d59ae]: Finished execution of actions

```

**Comment by nielsfaber** [comment] 2021-12-18 10:44
@Micha-Btz Thanks for checking this! I will update the code accordingly, such that it will be improved once again in the next release.

I also see that[ in the code](https://github.com/home-assistant/core/blob/3c66706a49e0d0a6147f352b6b8d425d7b874fae/homeassistant/components/fritzbox/climate.py#L132) of the fritzbox integration the hvac_mode is not compared against the current mode as suspected, which explains the observed behaviour.
Therefore you will probably see the same happening in the climate card when clicking on the flame icon:
![image](https://user-images.githubusercontent.com/16861605/146638179-57ddcf8a-f93c-4109-9520-6451b8ad15cd.png)
I don't think this is logical nor user friendly so I do think that changes are need in the fritzbox integration (a simple check for comparing requested hvac_mode with current hvac_mode would already help a lot). But I'm not going to follow-up on this myself, as I am not a user of it.

**Comment by Micha-Btz** [comment] 2021-12-18 10:55
@nielsfaber thank you a lot for your support. 

@all other from this issue
It would be good, that we all take the linked issue to the core https://github.com/home-assistant/core/issues/60823
and try to improve the code in general.

**Comment by pachi81** [comment] 2021-12-18 11:47
@nielsfaber Thank you for your work and support!
You are right, if I click on heat mode, the preset is set to comfort... I will add this to the core bug.

**Comment by nielsfaber** [comment] 2021-12-27 10:44
@Micha-Btz The last change as mentioned in https://github.com/nielsfaber/scheduler-component/issues/157#issuecomment-997168591 has been added to the new release v3.2.6. 
Since you already confirmed it works for fritzbox, I will close this issue as the problem should now be fixed for everyone.
I hope that changes will be made in the fritzbox integration as well, but this is beyond my control.
Thanks for the assistance with this bug 👍

**Closed by nielsfaber** 2021-12-27 10:44 UTC
Labels: bug, in development
