### ISSUE TITLE
HVAC Schedules

### ISSUE THREAD

**Issue by NIghtHawkATL** [nielsfaber/scheduler-component#133] opened 2021-10-21 01:50 UTC
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
When switching between schedules for heat and cool, if the switch is between schemes, the temperature set point should be updated to the right temperature for the mode. Say heat is set to 68°F and cool is set to 74°F. When switching from heat to cool, the set point of 74° should be sent along with the mode.

### Actual behavior
When switching off the heat schedule and switching on the cool schedule, the mode is changed but the set point stays the same from the heat mode schedule. If heat was set to 68° and the heat schedule is turned off and the cool schedule is turned on, the set point stays at 68° and is switched to cool mode. I have to manually change the set point to match what I have set in the clscheme.

### Steps to Reproduce
Create a heat or cool scheme with one thermostat and set a time for the set point to change during the day/night. Enable the schedule and then let it run. Creat a second scheduled scheme for heat. Set the setpoints for the different times throughout the day for it to change. Save it and disable it. Switch off the cool schedule and switch on the heat schedule. Then switch off the heat schedule and switch on the cool schedule. The set point doesn’t get updated but the mode does.

this is being done with 2 Honeywell ZWave thermostats.

bonus request: automatic disable the new schedule and make it to where it needs to be enabled before use. That way, it doesn’t always send the scheduled mode or set point right after creation. This is helpful if the air is running and you are creating a heating schedule and when you save, it automatically switches on the heat while the cool schedule is enabled as well.

**Comment by nielsfaber** [comment] 2021-10-21 05:50
I suggest to you to make a generic thermostat (see https://www.home-assistant.io/integrations/generic_thermostat/) and create the same schedule for this entity.
I believe all will work as you expect it and that the problem you are having is related to either your device or the zwave integration.

Please share the results. Preferably some screenshots of the schedule configurations and the history or logbook data showing what happens to the entity.

**Comment by nielsfaber** [comment] 2021-11-17 20:21
@NIghtHawkATL I released a new version v3.2.3 with some improvements which should fix the issue. Could you please update and confirm that the issue is solved for you? You can close the issue if so.

**Comment by NIghtHawkATL** [comment] 2021-11-18 01:37
Looks like it works now. I can see that the temp setpoint does jump up to the setpoint of the schedule but it doesn’t actually trigger the HVAC to turn on and then it switches to the correct mode.

I will check it out again tomorrow and see if it continues to work well.

—
Chris Patterson
Cell: 678-549-2725
LinkedIn: www.linkedin.com/in/cdpatterson

________________________________

**Comment by NIghtHawkATL** [comment] 2021-11-23 12:29
Looks to be fixed on the latest. Thanks for the heads up and the work you did!

—
Chris Patterson
Cell: 678-549-2725
LinkedIn: www.linkedin.com/in/cdpatterson

________________________________

**Closed** 2021-12-04 08:16 UTC
Labels: bug, in development

**Comment by NIghtHawkATL** [comment] 2022-03-18 01:44
Edited some of my posts to remove my number and LinkedIn link.
