### ISSUE TITLE
Service schedule.run_action always has error: current_timeslot() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by cascer1** [nielsfaber/scheduler-component#128] opened 2021-09-22 06:57 UTC
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
Running the service `schedule.run_action` runs the schedule at the current timeslot. For example for a thermostat:

- 00:00 - 16C
- 07:00 - 20C
- 10:00 - 16C
- 17:00 - 20C
- 22:00 - 16C

Running the service at 08:54 should set the target temperature to 20C.

### Actual behavior

The service execution fails with en unknown error. [Log file here](https://gist.github.com/cascer1/ace05c317d42d12dbfcb36949ace8254)

### Steps to Reproduce

1. Create a new schedule (I used the scheduler card)
2. Execute the service for the newly created schedule

**Comment by nielsfaber** [comment] 2021-09-22 11:13
>  I checked for similar existing issues (both open and closed) before posting.

Are you sure?
Duplicate of #123.

**Closed by nielsfaber** 2021-09-22 11:13 UTC
Labels: bug
