### ISSUE TITLE
Shedules turn unavailable after reboot under HA 2021.05b4 and need to be 'resaved'

### ISSUE THREAD

**Issue by gribouk** [nielsfaber/scheduler-component#104] opened 2021-05-02 08:20 UTC
I've updated HA to 2021.05b4 and scheduler to 3.1.0

After the reboot I experience following behavior - 9 out of ~20 shedules (!!! not all !!!) turn unavailable. But they are accessible for editing. I enter the shedule and have to chose 'save' and after that it turns available again.

This behaviour is unpredictible - I save the shedules and reboot several times no problem, but in a few hours after reboot it gives me the errors in the logs again and these 9 schedules are unavaialble again. 

The logs errors are attached below:

```
Logger: homeassistant.util.logging
Source: util/logging.py:105
First occurred: 11:10:59 (9 occurrences)
Last logged: 11:10:59

Exception in async_timer_updated when dispatching 'scheduler_timer_updated': ('e73111',) Traceback (most recent call last): File "/config/custom_components/scheduler/switch.py", line 191, in async_timer_updated await self._action_handler.async_queue_actions( File "/config/custom_components/scheduler/actions.py", line 194, in async_queue_actions await self.async_process_queue() File "/config/custom_components/scheduler/actions.py", line 234, in async_process_queue res = await self.async_execute_action(action, conditions, condition_type) File "/config/custom_components/scheduler/actions.py", line 278, in async_execute_action await async_call_from_config( File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 165, in async_call_from_config await hass.services.async_call(**params, blocking=blocking, context=context) File "/usr/src/homeassistant/homeassistant/core.py", line 1428, in async_call raise ServiceNotFound(domain, service) from None homeassistant.exceptions.ServiceNotFound: Unable to find service input_number.set_value
Exception in async_timer_updated when dispatching 'scheduler_timer_updated': ('9d028e',) Traceback (most recent call last): File "/config/custom_components/scheduler/switch.py", line 191, in async_timer_updated await self._action_handler.async_queue_actions( File "/config/custom_components/scheduler/actions.py", line 194, in async_queue_actions await self.async_process_queue() File "/config/custom_components/scheduler/actions.py", line 234, in async_process_queue res = await self.async_execute_action(action, conditions, condition_type) File "/config/custom_components/scheduler/actions.py", line 278, in async_execute_action await async_call_from_config( File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 165, in async_call_from_config await hass.services.async_call(**params, blocking=blocking, context=context) File "/usr/src/homeassistant/homeassistant/core.py", line 1428, in async_call raise ServiceNotFound(domain, service) from None homeassistant.exceptions.ServiceNotFound: Unable to find service input_number.set_value
Exception in async_timer_updated when dispatching 'scheduler_timer_updated': ('e5f3b8',) Traceback (most recent call last): File "/config/custom_components/scheduler/switch.py", line 191, in async_timer_updated await self._action_handler.async_queue_actions( File "/config/custom_components/scheduler/actions.py", line 194, in async_queue_actions await self.async_process_queue() File "/config/custom_components/scheduler/actions.py", line 234, in async_process_queue res = await self.async_execute_action(action, conditions, condition_type) File "/config/custom_components/scheduler/actions.py", line 278, in async_execute_action await async_call_from_config( File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 165, in async_call_from_config await hass.services.async_call(**params, blocking=blocking, context=context) File "/usr/src/homeassistant/homeassistant/core.py", line 1428, in async_call raise ServiceNotFound(domain, service) from None homeassistant.exceptions.ServiceNotFound: Unable to find service input_number.set_value
Exception in async_timer_updated when dispatching 'scheduler_timer_updated': ('7622aa',) Traceback (most recent call last): File "/config/custom_components/scheduler/switch.py", line 191, in async_timer_updated await self._action_handler.async_queue_actions( File "/config/custom_components/scheduler/actions.py", line 194, in async_queue_actions await self.async_process_queue() File "/config/custom_components/scheduler/actions.py", line 234, in async_process_queue res = await self.async_execute_action(action, conditions, condition_type) File "/config/custom_components/scheduler/actions.py", line 278, in async_execute_action await async_call_from_config( File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 165, in async_call_from_config await hass.services.async_call(**params, blocking=blocking, context=context) File "/usr/src/homeassistant/homeassistant/core.py", line 1428, in async_call raise ServiceNotFound(domain, service) from None homeassistant.exceptions.ServiceNotFound: Unable to find service input_number.set_value
Exception in async_timer_updated when dispatching 'scheduler_timer_updated': ('0dbf60',) Traceback (most recent call last): File "/config/custom_components/scheduler/switch.py", line 191, in async_timer_updated await self._action_handler.async_queue_actions( File "/config/custom_components/scheduler/actions.py", line 194, in async_queue_actions await self.async_process_queue() File "/config/custom_components/scheduler/actions.py", line 234, in async_process_queue res = await self.async_execute_action(action, conditions, condition_type) File "/config/custom_components/scheduler/actions.py", line 278, in async_execute_action await async_call_from_config( File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 165, in async_call_from_config await hass.services.async_call(**params, blocking=blocking, context=context) File "/usr/src/homeassistant/homeassistant/core.py", line 1428, in async_call raise ServiceNotFound(domain, service) from None homeassistant.exceptions.ServiceNotFound: Unable to find service input_boolean.turn_on
```

**Comment by nielsfaber** [comment] 2021-05-02 08:59
The logs indicate that some HA services do not exist.
Does this happen directly after startup?
Your logs show 5 issues, but your talking about 9 schedules, do all schedules have the same problem?

**Comment by gribouk** [comment] 2021-05-02 09:11
No, not all, and this is strange - axactly 9 items fall off every time. And I do not understand what triggers such a behaviour... My guess is that when you edit or add some new schedule, next boot is a problematic one, but it needs further inspection...

"The logs indicate that some HA services do not exist."
??? input_number.set_value does not exist ???

this record also says there are 9: "First occurred: 11:10:59 (9 occurrences)"

When I first encountered this, they all were from my climate shedules group. But today I've created one more shedule, and it were 8 from the previously falen off and the new one I've just created. So, I guess, there is a list of them at some point (probably on a start up) and 9 consequtive from this list fall off...

**Comment by nielsfaber** [comment] 2021-05-02 14:28
I could reproduce this issue and made a fix for it in https://github.com/nielsfaber/scheduler-component/commit/951c74744c44f8e67c76dabf96ca425e73999f37
If you want to help, could you manually update your `actions.py` file in custom_components/scheduler to this:
https://raw.githubusercontent.com/nielsfaber/scheduler-component/main/custom_components/scheduler/actions.py
After restarting HA the problem should not occur anymore.

**Comment by gribouk** [comment] 2021-05-02 18:10
I did it. First reboot went well. Now it will take some time to understand if it is gone forever, since, as I wrote, the etymology of the phenomena remains undiscovered to me... If it acures again, I'll let you know.

**Comment by nielsfaber** [comment] 2021-05-02 18:50
The problem was caused by the fact that the helper entities in HA (input_boolean, input_select, input_number, ...) have a different behaviour than others:
They do not start up with state "unknown" (which is an indication that its still being initialized) but in the state prior to shutdown of HA.
Their services (actions) are not registered in HA directly after startup, the problem was caused by scheduler being started before these helpers.
I added a check for the services being registered, which should take care of all such startup related issues.
I wouldn't worry about it coming back, but if you have problems, please let me know.

**Comment by nielsfaber** [comment] 2021-05-15 13:02
I will close this issue, assuming it is fixed now.
Let me know if you still see this problem.

**Closed by nielsfaber** 2021-05-15 13:02 UTC
Labels: bug, in development
