### ISSUE TITLE
"Unable to connect to Home Assistant"

### ISSUE THREAD

**Issue by pqpxo** [nielsfaber/scheduler-component#24] opened 2020-09-21 22:35 UTC
It took me quite some time to find the culprit but I was encountering an issue where I'd be able to use Home Assistant for about 5-10mins before getting a "Unable to connect to Home Assistant" error message. The fix was to clear my cookies in my browser. I came to realise (after systematic testing and trail and error) that this component caused the issue. Unfortunately I am unable to find any relevant logs to provide any hard evidence however after posting on Reddit and Facebook I've had someone else mention the same issue and resolution by removing this component.

**Comment by nielsfaber** [comment] 2020-09-22 04:09
Oh wow, that doesn't sound **really** bad.
I would like to find the root cause here, but it looks like that will not be easy.
I'm hoping you can help me finding this. 
Have you been successful with reproducing it? The issue comes back as soon as you add the scheduler again?

It _sounds_ like the issue is caused by the scheduler-card, not this component though.
Because the component has really nothing to do with browsers and cookies, it only does the timekeeping part on the background.
Simple way to proof this would be to keep the scheduler integration on (with some schedules running), and remove the card from your Lovelace config, see if the problem persists.

**Comment by pqpxo** [comment] 2020-09-22 11:19
Hi there,

I've had another 2-3 people on Facebook confirm that they've had the same issue and managed to resolve it by removing this component. I'll try and spin up another instance of HA and reproduce the issue, I'm not willing to risk my 'production' HA instance again

**Comment by KTibow** [comment] 2020-09-22 13:57
@pqpxo how'd it go?

**Comment by Kylespamaccoun7** [comment] 2020-09-22 18:25
Hi, this just happened to me this morning. I installed scheduler card, restarted three times trying to get it to work before I remembered I had to install an actual integration. 

Then I installed the integration via HACS and I had the error described above. Clearing cache did not work like frontend stuff normally does, but I was able to run on another browser and in incognito mode (chrome). 

I had to actually clear cookies as described above.  I didn't want to lose my sign-ins so I cleared the cookies individually. I cleared the database storage cookie and local storage cookies associated with the ip address and port HASS runs on.  Wish I had tried them individually. 

Sorry I don't have any logs available. I run hass version 0.108.8 on docker (virtual machine).  I wonder if the other users who had issues were running older versions as well.  Hope this helps.

**Comment by pqpxo** [comment] 2020-09-22 18:41
> Hi, this just happened to me this morning. I installed scheduler card, restarted three times trying to get it to work before I remembered I had to install an actual integration.
> 
> Then I installed the integration via HACS and I had the error described above. Clearing cache did not work like frontend stuff normally does, but I was able to run on another browser and in incognito mode (chrome).
> 
> I had to actually clear cookies as described above. I didn't want to lose my sign-ins so I cleared the cookies individually. I cleared the database storage cookie and local storage cookies associated with the ip address and port HASS runs on. Wish I had tried them individually.
> 
> Sorry I don't have any logs available. I run hass version 0.108.8 on docker (virtual machine). I wonder if the other users who had issues were running older versions as well. Hope this helps.

Hey there ... After many hours and trying to figure out the cause I actually downgraded to 0.114 and experienced the same issue. Initially I thought it was something new/introduced in 0.115 but it appears not

**Comment by pqpxo** [comment] 2020-09-22 18:47
> @pqpxo how'd it go?

Going to spin up another VM later this evening and give it a try. Is there anything I should be looking out for log wise or in the Network tab in Chrome Inspector? I spent ages trying to find an error or clue to what was causing the issue.

**Comment by nielsfaber** [comment] 2020-09-22 19:46
This issue is also posted in the `scheduler-card`: https://github.com/nielsfaber/scheduler-card/issues/59
I propose we continue the follow-up there. As it is _likely_ caused by the card.

**Comment by KTibow** [comment] 2020-09-22 19:49
Consider closing if just the scheduler-component doesn't cause any errors?

**Comment by nielsfaber** [comment] 2020-09-22 19:54
So far i don't know for sure whether the `scheduler-component` can be excluded from the equation...

**Comment by nielsfaber** [comment] 2020-09-27 14:10
I close this issue, assuming that this problem is fixed with new version of the card.
Please re-open if there are problems again.

**Closed by nielsfaber** 2020-09-27 14:10 UTC
Labels: bug
