### ISSUE TITLE
Not possible to set temperature with mobile app

### ISSUE THREAD

**Issue by JoeAstor** [nielsfaber/scheduler-component#226] opened 2022-11-26 20:12 UTC
### Checklist
- [x ] I checked for similar existing issues (both open and closed) before posting.
- [x ] I am running the latest version

### Expected behavior
Possibility to set temperature

### Actual behavior
When making a schedule, when wanthing to set temperature it always returns to 5°C.

**Comment by nielsfaber** [comment] 2022-12-01 20:17
Duplicate of https://github.com/nielsfaber/scheduler-card/issues/625

**Closed by nielsfaber** 2022-12-01 20:17 UTC
Labels: bug
