### ISSUE TITLE
DST (Daylight Saving Time) handling error

### ISSUE THREAD

**Issue by lmagyar** [nielsfaber/scheduler-component#94] opened 2021-03-28 10:46 UTC
HA: core-2021.3.4
scheduler-component: v3.0.4
scheduler-card: v2.0.5

---

The fist event after DST change misses the correct moment with 1 hour, the next events work correctly.

I think the problem is here [helpers.py#L57](https://github.com/nielsfaber/scheduler-component/blob/main/custom_components/scheduler/helpers.py#L57)

```
        time = dt_util.parse_time(time)
        time = time.replace(tzinfo=dt_util.now().tzinfo)

        today = dt_util.now().date()
        time_obj = datetime.datetime.combine(today, time)
```

Scheduler stores the schedule timeslots is local time, like:

```
    "data": {
        "schedules": [
            {
                "schedule_id": "6ad0bf",
                "timeslots": [
                    {
                        "start": "00:00:00",
                        "stop": "07:00:00",
```

At midnight it tries to calculate the `07:00:00` local time in ISO-8601 format, and at midnight the time zone is `+0100`, so it calculates `2021-03-28T07:00:00+0100` (UTC `06:00:00`). But at `02:00` due to DST, the timezone changes to `+0200`, so the time trigger misses 1 hour, after `02:00` the correct moment is `2021-03-28T07:00:00+0200` (UTC `05:00:00`).

So local time calculations should be handled by some system functions (I'm not familiar with Python, so I don't know how, but `date` (it is independent from DST) + `local time` together should be converted to UTC or ISO-8601 format, and not time separately), because the system and Home Assistant handles the time zone and the nightmare of DST correctly. And yes, if somebody enters 02:30 local time, he has a problem...

**Comment by nielsfaber** [comment] 2021-03-28 11:03
Duplicate of https://github.com/nielsfaber/scheduler-card/issues/354
It will be taken care of in the next update.

**Closed by nielsfaber** 2021-03-28 11:03 UTC

**Comment by platte-73** [comment] 2023-03-26 17:24
I also having problems with Daylight Saving Time. Time in home assistant is correct but schedular still using the old Time. Will there be a fix or do I have to change something
