### ISSUE TITLE
conditions dont allow.... conditions

### ISSUE THREAD

**Issue by magiva** [nielsfaber/scheduler-component#291] opened 2023-09-28 13:55 UTC
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
[What you expected to happen]
when i selected conditions, i thought i could set one for if anyone was home, use a boolean entity etc but it asked for other climate entities.

### Actual behavior
[What actually happened
conditions asked for climate entities only

### Steps to Reproduce
[Explain how to see the behaviour]
add a condition

if this is not a feature then it really should be as it makes sense to have a schedule that only activates if someone is home, in a room etc

**Comment by nielsfaber** [comment] 2023-09-28 15:18
Duplicate of #292

**Closed by nielsfaber** 2023-09-28 15:18 UTC
Labels: bug

**Comment by magiva** [comment] 2023-09-28 16:29
this is not closed as detailed in #292 this does not work, i can only select from the climate group
